<div class="row" id="kontakt">
    <div class="container" >
        <div class="row">

            <div class="col-md-6 maps" >
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d89226.40121928565!2d18.697840541213026!3d45.66437477031765!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x475cdb69395a73dd%3A0x153f912479587f19!2sHotel+Lug!5e0!3m2!1shr!2shr!4v1565432912891!5m2!1shr!2shr" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>

            <div class="col-md-6">
                <h2 class="text-uppercase mt-3 font-weight-bold text-white">Kontakt</h2>
                <form action="">
                <div class="row">

                    <div class="col-lg-6">
                    <div class="form-group">
                        <input type="text" class="form-control mt-2" placeholder="Ime/Tvrtka" required>
                    </div>
                    </div>

                    <div class="col-lg-6">
                    <div class="form-group">
                        <input type="text" class="form-control mt-2" placeholder="Adresa" required>
                    </div>
                    </div>

                    <div class="col-lg-6">
                    <div class="form-group">
                        <input type="email" class="form-control mt-2" placeholder="Email" required>
                    </div>
                    </div>

                    <div class="col-lg-6">
                    <div class="form-group">
                        <input type="number" class="form-control mt-2" placeholder="Telefon" required>
                    </div>
                    </div>

                    <div class="col-12">
                    <div class="form-group">
                        <textarea class="form-control" id="exampleFormControlTextarea1" placeholder="Unesite tekst" rows="4" required></textarea>
                    </div>
                    </div>

               
                    <div class="col-12">
                    <button class="btn btn-primary" type="submit">Pošalji</button>
                    </div>
                </div>
                </form>

                <div class="text-white">
                    <h2 class="text-uppercase mt-4 font-weight-bold">Hotel Lug</h2>

                    <i class="fas fa-phone mt-3"></i> <a href="tel:+">(+385) 031/123-456</a><br>
                    <i class="fas fa-phone mt-3"></i> <a href="tel:+">(+385) 031/123-456</a><br>
                    <i class="fa fa-envelope mt-3"></i> <a href="">info@hotel.hr</a><br>
                    <i class="fas fa-globe mt-3"></i> Glavna ulica 51, 31328 Lug<br>
                
                    <div class="my-4">
                        <a href=""><i class="fab fa-facebook fa-3x pr-4"></i></a>
                        <a href=""><i class="fab fa-linkedin fa-3x"></i></a>
                    </div>
                </div>

            
        </div>    
    </div>
</div>