<!doctype html>
<html class="no-js" lang="en" dir="ltr">
  <head>
    <?php include_once "template/head.phtml" ?>
  </head>
  <body>
    <div class="grid-container">
        <?php include_once "template/izbornik.phtml" ?>
        <div class=callout>
            <?php echo $content; ?>
        </div>
        <?php include_once "template/podnozje.phtml" ?>
    </div>
    <?php include_once "template/skripte.phtml" ?>
  </body>
</html>
