<body>
<div class="container">
    <div class="row">
      <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
        <div class="card card-signin my-5">
          <div class="card-body">
          <form class="log-in-form" method="post" action="<?php echo App::config('url'); ?>index/autoriziraj">
          <form>
            <fieldset>
            <h4 class="card-title text-center">Prijava</h4>
            <form class="form-signin">
            <div class="form-group">
              <label>Email
              <input type="email" class="form-control" name="email" id="email"
               <?php if (App::config('dev')) {
    echo ' value="edunova@edunova.hr"';
}?> />
            </label>
      
             </div>
            <div class="form-group">
            <label>Password
            <input type="password" class="form-control" name="password" id="password" 
            <?php if (App::config('dev')) {
    echo ' value="edunova"';
}?> />
            
            </div>
            </fieldset>
            <p><input type="submit" class="btn btn-info" value="Log in" /></p>
            <p><?php if (isset($greska)) {
    echo $greska;
} ?></p>

        </form>
        
        </div>
      </div>
    </div>
  </div>
</div>
</body>
