<div class="grid-x grid-margin-x">
    <div class="cell large-4 large-offset-4">
        <form class="log-in-form" method="post" 
        action="<?php echo App::config('url'); ?>index/autoriziraj">
            <h4 class="text-center">Prijava</h4>
            <label>Email
                <input type="email" name="email" id="email" 
                <?php if (App::config('dev')) {
    echo ' value="edunova@edunova.hr"';
}?> />
            </label>
            <label>Password
                <input type="password" name="password" id="password" 
                <?php if (App::config('dev')) {
    echo ' value="edunova"';
}?> />
            </label>
            <p><input type="submit" class="button expanded" value="Log in" /></p>
            <p><?php if (isset($greska)) {
    echo $greska;
} ?></p>
        </form>
    </div>
</div>
