<form>
    <div class="form-row">
    <div class="form-group col-md-6">
        <legend>Popunite tražene podatke</legend>

        <?php echo Utility::inputText(
            isset($greska) ? $greska : null, 'ime', 'Ime'); ?>

        <?php echo Utility::inputText(
            isset($greska) ? $greska : null, 'prezime', 'Prezime'); ?>

        <?php echo Utility::inputText(
            isset($greska) ? $greska : null, 'adresa', 'Adresa'); ?>

        <?php echo Utility::inputText(
            isset($greska) ? $greska : null, 'grad', 'Grad'); ?>

        <?php echo Utility::inputText(
            isset($greska) ? $greska : null, 'drzava', 'Država'); ?>

        <?php echo Utility::inputText(
            isset($greska) ? $greska : null, 'kontakt', 'Kontakt'); ?>
    </div>
    </div>
</form>
<hr />