
<a href="<?php echo App::config('url'); ?>kupac/pripremaNovi" 
class="btn btn-primary">
<i class="fas fa-plus-square"></i>
Dodaj novog kupca </a>

<form class="form-inline" 
    action="<?php echo App::config('url'); ?>kupac/index" 
    method="get">
  <div class="input-group md-form form-sm form-1 pl-0">
    <div class="input-group-prepend">
   
    <input class="form-control mr-sm-2" type="search" name="uvjet" id="uvjet" 
      placeholder="unesite uvjet pretraživanja" aria-label="Search"
      value="<?php echo App::param('uvjet'); ?>" />
    <button class="btn btn-primary" type="submit">Traži</button> 
  
  </div>
  </div>
</form>
<div class="table-responsive-sm">
    <div class="kupci">
       <table id="tablicaKupci">  
        <table class="table">  
          <thead>
            <tr class="table-secondary">
            <th scope="col">Ime</th>
            <th scope="col">Prezime</th>
            <th scope="col">Adresa</th>
            <th scope="col">Grad</th>
            <th scope="col">Država</th>
            <th scope="col">Kontakt</th>
            <th scope="col">Promjena/Brisanje</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($kupci as $kupac): ?>
            <tr class="table-info">
                <td><?php echo $kupac->ime; ?></td>
                <td><?php echo $kupac->prezime; ?></td>
                <td><?php echo $kupac->adresa; ?></td>
                <td><?php echo $kupac->grad; ?></td>
                <td><?php echo $kupac->drzava; ?></td>
                <td><?php echo $kupac->kontakt; ?></td>
                <td>
                <a title="Promjeni <?php echo $kupac->ime; ?>" 
                    href="<?php
                    echo App::config('url');
                    ?>kupac/pripremaPromjeni/<?php echo $kupac->sifra; ?>">
                    <i class="fas fa-edit fa-2x" style="color: orange"></i>
                </a>
                <?php if ($kupac->ukupno == 0): ?>
                    <a title="Obriši <?php echo $kupac->ime; ?>" 
                        href="<?php
                        echo App::config('url');
                        ?>kupac/brisanje/<?php echo $kupac->sifra; ?>">
                        <i class="fas fa-trash fa-2x" style="color: red"></i>
                    </a>
            <?php else:?>
                    <i title="Ne može se obrisati jer ima rezervacija" 
                    class="fas fa-trash fa-2x" style="color: gray"></i>

                <?php endif; ?> 
                
                </td>
              </tr> 
            <?php endforeach; ?>
          </tbody>
    </table>
  </table>
</div>
</div>

