<a href="<?php echo App::config('url'); ?>kupac/pripremaNovi" 
class="btn btn-primary">
<i class="fas fa-plus-square"></i>
Dodaj novog kupca</a>

<table id="tablicaKupci">  
  <table class="table table-hover">  
    <thead>
      <tr class="table-secondary">
      <th scope="col">Ime</th>
      <th scope="col">Prezime</th>
      <th scope="col">Adresa</th>
      <th scope="col">Grad</th>
      <th scope="col">Država</th>
      <th scope="col">Kontakt</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($kupci as $kupac): ?>
      <tr class="table-info">
          <td><?php echo $kupac->ime; ?></td>
          <td><?php echo $kupac->prezime; ?></td>
          <td><?php echo $kupac->adresa; ?></td>
          <td><?php echo $kupac->grad; ?></td>
          <td><?php echo $kupac->drzava; ?></td>
          <td><?php echo $kupac->kontakt; ?></td>
          <td>
          <a title="Promjeni <?php echo $kupac->ime; ?>" 
              href="<?php
              echo App::config('url');
              ?>kupac/pripremaPromjeni/<?php echo $kupac->sifra; ?>">
              <i class="fas fa-edit fa-2x" style="color: orange"></i>
          </a>
          <?php if ($kupac->ukupno == 0): ?>
              <a title="Obriši <?php echo $kupac->ime; ?>" 
                  href="<?php
                  echo App::config('url');
                  ?>kupac/brisanje/<?php echo $kupac->sifra; ?>">
                  <i class="fas fa-trash fa-2x" style="color: red"></i>
              </a>
      <?php else:?>
              <i title="Ne može se obrisati jer ima rezervacija" 
              class="fas fa-trash fa-2x" style="color: gray"></i>

          <?php endif; ?> 
          
          </td>
        </tr> 
      <?php endforeach; ?>
    </tbody>
    <tfoot>
      <tr>
        
      </tr>
    </tfoot>
</table>