<div class="container"> 
    <div class="row">
        <div class="col-lg-6 lg-offset-6">
            <form method="post"
            action="<?php echo App::config('url'); ?>kupac/novi">
            <?php include_once 'detalji.phtml'; ?>
                <div class="container">
                        <div class="col-xs-6 col-lg-3">
                            <a class="btn btn-danger"
                            href="<?php echo App::config('url'); ?>kupac/index">
                                Odustani
                            </a>            
                    </div>
                    <div class="col-lg-1 col-sm-1 ">
                        
                    </div>
                
                    <div class="col-sm-6 col-lg-8">
                        <input type="submit" class="btn btn-info" value="Dodaj novog kupca">      
                        </div>  
                    </div>        
            </form>
        </div>
    </div>
</div>
