<h1>Tablice</h1>

<table id="tablicaKupci">
  <thead>
    <tr>
     <th>Ime</th>
     <th>Prezime</th>
     <th>Adresa</th>
     <th>Grad</th>
     <th>Država</th>
     <th>Kontakt</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($kupci as $kupac): ?>
      <tr>
        <td><?php echo $kupac->ime; ?></td>
        <td><?=$kupac->prezime; ?></td>
        <td><?php echo $kupac->adresa; ?></td>
        <td><?php echo $kupac->grad; ?></td>
        <td><?php echo $kupac->drzava; ?></td>
        <td><?php echo $kupac->kontakt; ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
  <tfoot>
    <tr>
      
    </tr>
  </tfoot>
</table>

