<div class="container"> 
    <div class="row">
        <div class="col-lg-6">
            <form method="post" 
                action="<?php echo App::config('url'); ?>kupac/promjeni/<?php echo $id; ?>">
                <?php include_once 'detalji.phtml'; ?>
                    <div class="container">
                        <div class="col-sm-6 col-lg-3">
                            <a class="btn btn-warning"
                                href="<?php echo App::config('url'); ?>kupac/index">
                                Odustani
                            </a>
                        </div>
                        <div class="col-1 col-lg-1">
                        
                        </div>
                        <div class="col-6 col-lg-8">
                            <input class="btn btn-info"
                                type="submit" value="Promjeni">
                        </div>
                    </div>               
            </form>
        </div>
    </div>
</div>


<form action="" method="post">
    <!-- User's Credentials  -->
    <fieldset class="form-group">
        <div class="row">
            <legend class="col-md-3 col-form-label pt-0"></legend>
            <div class="col-md-9">
                <div class="form-group col-md-4">
                    <label for="username">Username:</label>
                    <input type="text" class="form-control username" id="username" placeholder="Username..." name="username">
                </div>
                <div class="form-group col-md-4">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control email" id="email" placeholder="Email..." name="email">
                </div>
                <div class="form-group col-md-4">
                    <label for="password">Password:</label>
                    <input type="password" class="form-control password" id="password" placeholder="Password..." name="password">
                </div>
            </div>
        </div>
    </fieldset>