<meta charset="utf-8"> 
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?php echo APP::config('nazivApp'); ?></title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/bootstrap.min.css">
<?php if (isset($cssFile)) {
    echo $cssFile."\n";
}?>
<link rel="stylesheet" href="<?php echo APP::config('url'); ?>public/css/app.css">
<script src="https://kit.fontawesome.com/3b8c308efb.js"></script>
