<div clas="container-fluid">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Izbornik</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item-active"<?php echo Utility::active('/'); //ne radi?>>
        <a class="nav-link text-white" href="<?php echo App::config('url'); ?>">
            <?php echo App::config('nazivApp'); ?>
        </a>
      </li>

        <?php if (isset($_SESSION['autoriziran'])): ?>
        <li class="nav-item" <?php echo Utility::active('/index/nadzornaPloca'); ?>>
          <a class="nav-link text-white" href="<?php echo App::config('url'); ?>index/nadzornaPloca">Nadzorna ploča</a>
        </li>
        <li class="nav-item" <?php echo Utility::active('/smjer/index'); ?>>
          <a class="nav-link text-white" href="<?php echo App::config('url'); ?>smjer/index">Smjerovi</a>
        </li>
        <li class="nav-item" <?php echo Utility::active('/grupa/index'); ?>>
          <a class="nav-link text-white" href="<?php echo App::config('url'); ?>grupa/index">Grupe</a>
        </li>
        <li class="nav-item" <?php echo Utility::active('/polaznik/index'); ?>>
          <a class="nav-link text-white" href="<?php echo App::config('url'); ?>polaznik/index">Polaznici</a>
        </li>
        <li class="nav-item" <?php echo Utility::active('/predavac/index'); ?>>
          <a class="nav-link text-white" href="<?php echo App::config('url'); ?>predavac/index">Predavači</a>
        </li>
      <?php endif; ?>
  </div>
      <div class="navbar-nav">
      <a class="nav-item nav-link text-white" href="<?php echo APP::config('url'); ?>index/onama">O nama</a>
      <a class="nav-item nav-link text-white" href="<?php echo APP::config('url'); ?>index/kontakt">Kontakt</a>
        <?php if (isset($_SESSION['autoriziran'])): ?>
          <a class="nav-item nav-link text-white" href="<?php echo App::config('url'); ?>index/logout">Odjava
        <?php echo $_SESSION['autoriziran']->imePrezime; ?></a>
          <?php else:?>
          <a class="nav-item nav-link text-white" href="<?php echo App::config('url'); ?>index/login">Prijava</a>
        <?php endif; ?>
        
    </div>
  
</nav>
</div>
