<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Izbornik</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li<?php echo Utility::active('/'); //ne radi?>>
        <a href="<?php echo App::config('url'); ?>">
            <?php echo App::config('nazivApp'); ?>
        </a>
      </li>

      <?php if (isset($_SESSION['autoriziran'])): ?>
        <li<?php echo Utility::active('/index/nadzornaPloca'); ?>>
          <a href="<?php echo App::config('url'); ?>index/nadzornaPloca">Nadzorna ploča</a>
        </li>
        <li<?php echo Utility::active('/smjer/index'); ?>>
          <a href="<?php echo App::config('url'); ?>smjer/index">Smjerovi</a>
        </li>
        <li<?php echo Utility::active('/grupa/index'); ?>>
          <a href="<?php echo App::config('url'); ?>grupa/index">Grupe</a>
        </li>
        <li<?php echo Utility::active('/polaznik/index'); ?>>
          <a href="<?php echo App::config('url'); ?>polaznik/index">Polaznici</a>
        </li>
        <li<?php echo Utility::active('/predavac/index'); ?>>
          <a href="<?php echo App::config('url'); ?>predavac/index">Predavači</a>
        </li>
      <?php endif; ?>

      <li<?php echo Utility::active('/index/onama'); ?>>
        <a href="<?php echo App::config('url'); ?>index/onama">O nama</a>
      </li>
      <li<?php echo Utility::active('/index/kontakt'); ?>>
        <a href="<?php echo App::config('url'); ?>index/kontakt">Kontakt</a>
      </li> 
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <li>
      <?php if (isset($_SESSION['autoriziran'])): ?>
        <a href="<?php echo App::config('url'); ?>index/logout">Odjava
        <?php echo $_SESSION['autoriziran']->imePrezime; ?></a>
      <?php else:?>
        <a href="<?php echo App::config('url'); ?>index/login">Prijava</a>
      <?php endif; ?>
      </li>
    </ul>
  </div>
</div>