<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Izbornik</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <a class="nav-item nav-link active" href="<?php echo App::config('url'); ?>">
            <?php echo App::config('nazivApp'); ?>
      </a>
      <a class="nav-item nav-link" href="<?php echo App::config('url'); ?>index/onama">O nama</a>
      <a class="nav-item nav-link" href="<?php echo App::config('url'); ?>index/kontakt">Kontakt</a>
    </div>
  </div>
  
  <form class="form-inline my-2 my-lg-0">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Odjava</button>
  </form>
  
</nav>