<script src="<?php echo APP::config('url'); ?>public\js\bootstrap.bundle.js"></script>
<script src="<?php echo APP::config('url'); ?>public\js\bootstrap.bundle.js.map"></script>
<script src="<?php echo APP::config('url'); ?>public\js\bootstrap.bundle.min.js"></script>
<script src="<?php echo APP::config('url'); ?>public\js\bootstrap.bundle.min.js"></script>
<script src="<?php echo APP::config('url'); ?>public\js\bootstrap.js"></script>
<script src="<?php echo APP::config('url'); ?>public\js\bootstrap.js.map"></script>
<script src="<?php echo APP::config('url'); ?>public\js\bootstrap.min.js"></script>
<script src="<?php echo APP::config('url'); ?>public\js\bootstrap.min.js.map"></script>