<div class="container"> 
    <div class="row">
        <div class="col-lg-6">
            <form method="post" 
                action="<?php echo App::config('url'); ?>rezervacija/novi">
                <?php include_once 'detalji.phtml'; ?>
                    <div class="container">
                        <div class="col-sm-5 col-lg-3">
                            <a class="btn btn-danger"
                                href="<?php echo App::config('url'); ?>rezervacija/index">
                                Odustani
                            </a>
                        </div>
                        <div class="col-sm-1 col-lg-1">
                        
                        </div>
                        <div class="col-sm-6 col-lg-8">
                            <input class="btn btn-info"
                                type="submit" value="Dodaj novu rezervaciju">
                        </div>
                    </div>               
            </form>
        </div>
    </div>
</div>