<a href="<?php echo App::config('url'); ?>placanje/pripremaNovi" 
class="btn btn-primary">
<i class="fas fa-plus-square"></i>
Dodaj novo plaćanje</a>

<div class="container">

    
    <?php foreach ($placanja as $placanje): ?>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <ul class="list-group">
                <li class="list-group-item list-group-item-info"><?php echo $placanje->nacinplacanja; ?></li>
                <li class="list-group-item">
                    <a title="Promjeni <?php echo $placanje->nacinplacanja; ?>" 
                        href="<?php
                        echo App::config('url');
                        ?>placanje/pripremaPromjeni/<?php echo $placanje->sifra; ?>">
                        <i class="fas fa-edit fa-2x" style="color: orange"></i>
                    </a>
                    <?php if ($placanje->ukupno == 0): ?>
                        <a title="Obriši <?php echo $placanje->nacinplacanja; ?>" 
                            href="<?php
                            echo App::config('url');
                            ?>placanje/brisanje/<?php echo $placanje->sifra; ?>">
                            <i class="fas fa-trash fa-2x" style="color: red"></i>
                        </a>
                    <?php else:?>
                        <i title="Ne može se obrisati jer ima unesene vrijednosti" 
                        class="fas fa-trash fa-2x" style="color: gray"></i>
                    <?php endif; ?>

                </li>
            </ul>
        </div>
    <?php endforeach; ?>
</div>
</div>

