<div class="row">
    <div class="col-xs-9 col-md-6 col-lg-3">
        <legend>Popunite tražene podatke</legend>

            <div class="col-xs-9 col-md-6 col-lg-3 text-light">
                <?php echo Utility::inputText(
                    isset($greska) ? $greska : null, 'vrstasobe', 'Vrsta sobe'); ?>                
                
                <?php echo Utility::inputText(
                    isset($greska) ? $greska : null, 'cijenasobe', 'Cijena sobe'); ?>
                
                <?php echo Utility::inputText(
                    isset($greska) ? $greska : null, 'slikasobe', 'Slika sobe'); ?>

                <?php echo Utility::inputText(
                    isset($greska) ? $greska : null, 'opissobe', 'Opis sobe'); ?>

            </div>

    </div>
</div>

<hr />