<div class="row">
    <div class="col-xs-9 col-md-6 col-lg-3">
        <legend>Popunite tražene podatke</legend>

            <div class="col-xs-9 col-md-6 col-lg-3 text-light">
                <?php echo Utility::inputText(
                    isset($greska) ? $greska : null, 'vrstasobe', 'Naziv sobe'); ?>                
                
                <?php echo Utility::inputText(
                    isset($greska) ? $greska : null, 'cijenasobe', 'Cijena sobe'); ?>
                
                <label for="slikasobe">Slika sobe</label>
                <select name="slikasobe" id="slikasobe">
                 <option value="0">Odaberite sliku sobe</option>
                 <?php foreach ($slikesoba as $slikasobe): ?>
                     <option 
                     
                     <?php echo App::param('slikasobe') == $slikasobe->sifra ? 'selected="selected"' : ''; ?>
                     
                     value="<?php echo $slikasobe->sifra; ?>"> 
                         <?php echo $slikasobe->slika; ?>
                     </option>
                <?php endforeach; ?>
                </select>

                <?php echo Utility::inputText(
                    isset($greska) ? $greska : null, 'opissobe', 'Opis sobe'); ?>

            </div>

    </div>
</div>

<hr /> 